# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25ffd6212aa8cfd722f36b66e4e2432f7ca01ea4d3c4232dbd71b69e974fcabd853d7e7d221d32184313a7672bb7f649685a0f689493b5e24b3a07284d2c3245

test:
  secret_key_base: 038fcbc55283442176c8e71bbf3a4e117e846e678fe4fd0d86aeb111715194661f7b9f32ed340356273c81ee95e65cc35413cace64ed82dea2e7ca83ad1ca28d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: ENV["SECRET_KEY_BASE"]
